### ISSUE TITLE
Specify which architecture to use for install59.fs file download

### ISSUE THREAD

**Issue by cniesen** [elad/openbsd-apu2#4]
The install59.fs file exist in multiple architectures.  It would be good to specify which one one should use. 

I assume it's the amd64/install59.fs but don't have any actual experience if that's correct.

**Comment by elad** [comment]
You're right. It was supposed to be a download link, but GitHub's markdown syntax doesn't seem to support ftp://. Changed it to http:// + updated the path to use the release rather than snapshot. Thanks for the report!

**Comment by cniesen** [comment]
Thanks.  BTW for Microsoft Windows use Rawrite32 to write the installer image to the flash drive.
http://www.netbsd.org/~martin/rawrite32/

**Comment by elad** [comment]
Feel free to submit a PR...
