### ISSUE TITLE
Setting com0 now done by installer.

### ISSUE THREAD

**Issue by vanhecke** [elad/openbsd-apu2#6]
Hey,

thanks for the guide!
FYI - this now happens during the 6.0 install:

```
Change the default console to com0? [yes]
Available speeds are: 9600 19200 38400 57600 115200.
Which speed should com0 use? (or 'done') [115200]
```

So there's no reason to change `/etc/boot.conf` manually anymore.

PS. My APU2 was already on latest BIOS, so no need to update :)

**Comment by elad** [comment]
Could you please submit a PR for that? :)

(the BIOS update is there because at some point someone will need to know how to do it...)
